### ISSUE TITLE
ValueError: Input arrays should have the same number of samples as target arrays. Found 200 input samples and 1800 target samples.

### ISSUE THREAD

**Issue by WindHunter-Yang** [samiarja/sentiment-analysis#1]
When I run it, there are a error:ValueError: Input arrays should have the same number of samples as target arrays. Found 200 input samples and 1800 target samples.  How to solve it?

**Comment by WindHunter-Yang** [comment]
I got it,I should use the dataseet of zip,thanks for your contribution.

**Comment by samiarja** [comment]
Thanks for pointing this out, I will close this issue since it is solved
